"""Partial stub — the diskcache.Cache surface used here; rest via __getattr__."""

from __future__ import annotations

from typing import Any, Self

class Cache:
    """Disk-backed cache with a dict-like, pickling interface."""

    def __init__(self, directory: str | None = ..., *args: Any, **kwargs: Any) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *exc: object) -> None: ...
    def get(self, key: Any, default: Any = ...) -> Any: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
