"""Type stubs for playwright_stealth.stealth."""

from typing import Any

class Stealth:
    def __init__(self, **kwargs: Any) -> None: ...
    def use_async(self, ctx: Any) -> Any: ...
    async def apply_stealth_async(self, page_or_context: Any) -> None: ...
