"""Type stubs for typer CLI framework."""

from __future__ import annotations

from collections.abc import Callable
from typing import Any, TypeVar

_F = TypeVar('_F', bound=Callable[..., Any])

class Typer:
    def __init__(self, *, help: str = '', **kwargs: Any) -> None: ...
    def __call__(self, **kwargs: Any) -> None: ...
    def command(self, name: str = '', **kwargs: Any) -> Callable[[_F], _F]: ...

def Option(default: Any = ..., *param_decls: str, help: str = '', **kwargs: Any) -> Any: ...
def Argument(default: Any = ..., *, help: str = '', **kwargs: Any) -> Any: ...
