"""Claude Code internal API schemas."""

from __future__ import annotations

from src.schemas.cc_internal_api.base import EmptyBody, FromSdk, FromSession, PermissiveModel
from src.schemas.cc_internal_api.common import ApiCacheCreation, ApiUsage, CacheControl
from src.schemas.cc_internal_api.internal_endpoints import (
    KNOWN_FEATURE_FLAGS,
    AccountSettingsResponse,
    ClientDataResponse,
    CountTokensRequest,
    CountTokensResponse,
    DismissedBanner,
    EvalAttributes,
    EvalRequest,
    EvalResponse,
    ExperimentConfig,
    ExperimentResult,
    FeatureSource,
    FeatureValue,
    GroveResponse,
    HelloResponse,
    MetricDefinition,
    MetricsDataPoint,
    MetricsEnabledResponse,
    MetricsRequest,
    MetricsResponse,
    ModelAccessResponse,
    PaprikaMode,
    ReferralCodeDetails,
    ReferralEligibilityResponse,
)
from src.schemas.cc_internal_api.rate_limits import (
    FallbackStatus,
    OverageStatus,
    RateLimitStatus,
    RateLimitWindow,
    RepresentativeClaim,
    UnifiedRateLimit,
)
from src.schemas.cc_internal_api.request import (
    ContextManagementEdit,
    MessagesRequest,
    RequestContentBlock,
    RequestContextManagement,
    RequestMessage,
    RequestMetadata,
    RequestThinkingBlock,
    SystemBlock,
    TextContentBlock,
    ThinkingConfig,
    ToolDefinition,
    ToolInputSchema,
)
from src.schemas.cc_internal_api.response import (
    MessagesResponse,
    ResponseContent,
    ResponseContextManagement,
    ResponseTextContent,
    StopReason,
    ThinkingContent,
    ToolUseContent,
)
from src.schemas.cc_internal_api.statsig import (
    StatsigCustom,
    StatsigCustomIDs,
    StatsigEnvironment,
    StatsigEvent,
    StatsigEventMetadata,
    StatsigInitializeFullBody,
    StatsigInitializeRequest,
    StatsigInitializeResponse,
    StatsigMetadata,
    StatsigRegisterRequest,
    StatsigRegisterResponse,
    StatsigUser,
)
from src.schemas.cc_internal_api.streaming import (
    ContentBlockDeltaEvent,
    ContentBlockStart,
    ContentBlockStartEvent,
    ContentBlockStopEvent,
    DeltaContent,
    ErrorEvent,
    InitialMessage,
    InitialUsage,
    InputJsonDelta,
    MessageDeltaContextManagement,
    MessageDeltaEvent,
    MessageDeltaPayload,
    MessageDeltaUsage,
    MessageStartEvent,
    MessageStopEvent,
    PingEvent,
    SignatureDelta,
    SSEEvent,
    TextBlockStart,
    TextDelta,
    ThinkingBlockStart,
    ThinkingDelta,
    ToolUseBlockStart,
)
from src.schemas.cc_internal_api.telemetry import (
    KNOWN_EVENT_NAMES,
    Arch,
    ClientType,
    Entrypoint,
    Platform,
    TelemetryBatchRequest,
    TelemetryBatchResponse,
    TelemetryEnv,
    TelemetryEvent,
    TelemetryEventData,
    UserType,
)

__all__ = [
    # Base
    'EmptyBody',
    'FromSdk',
    'FromSession',
    'PermissiveModel',
    # Common
    'ApiCacheCreation',
    'ApiUsage',
    'CacheControl',
    # Request
    'ContextManagementEdit',
    'MessagesRequest',
    'RequestContentBlock',
    'RequestContextManagement',
    'RequestMessage',
    'RequestMetadata',
    'RequestThinkingBlock',
    'SystemBlock',
    'TextContentBlock',
    'ThinkingConfig',
    'ToolDefinition',
    'ToolInputSchema',
    # Response
    'MessagesResponse',
    'ResponseContent',
    'ResponseContextManagement',
    'ResponseTextContent',
    'StopReason',
    'ThinkingContent',
    'ToolUseContent',
    # Streaming - Events
    'SSEEvent',
    'MessageStartEvent',
    'ContentBlockStartEvent',
    'ContentBlockDeltaEvent',
    'ContentBlockStopEvent',
    'MessageDeltaEvent',
    'MessageStopEvent',
    'PingEvent',
    'ErrorEvent',
    # Streaming - Content blocks
    'ContentBlockStart',
    'TextBlockStart',
    'ThinkingBlockStart',
    'ToolUseBlockStart',
    # Streaming - Deltas
    'DeltaContent',
    'TextDelta',
    'ThinkingDelta',
    'SignatureDelta',
    'InputJsonDelta',
    # Streaming - Message parts
    'InitialMessage',
    'InitialUsage',
    'MessageDeltaPayload',
    'MessageDeltaUsage',
    'MessageDeltaContextManagement',
    # Rate Limits
    'UnifiedRateLimit',
    'RateLimitWindow',
    'RateLimitStatus',
    'OverageStatus',
    'FallbackStatus',
    'RepresentativeClaim',
    # Telemetry
    'TelemetryBatchRequest',
    'TelemetryBatchResponse',
    'TelemetryEvent',
    'TelemetryEventData',
    'TelemetryEnv',
    'KNOWN_EVENT_NAMES',
    # Telemetry type aliases
    'Platform',
    'Arch',
    'Entrypoint',
    'ClientType',
    'UserType',
    # Internal endpoints - Count tokens
    'CountTokensRequest',
    'CountTokensResponse',
    # Internal endpoints - Grove/Metrics
    'GroveResponse',
    'MetricsRequest',
    'MetricsResponse',
    'MetricDefinition',
    'MetricsDataPoint',
    'MetricsEnabledResponse',
    # Internal endpoints - Feature flags
    'EvalRequest',
    'EvalResponse',
    'EvalAttributes',
    'FeatureValue',
    'FeatureSource',
    'ExperimentConfig',
    'ExperimentResult',
    'KNOWN_FEATURE_FLAGS',
    # Internal endpoints - OAuth
    'AccountSettingsResponse',
    'ClientDataResponse',
    'DismissedBanner',
    'PaprikaMode',
    'ReferralCodeDetails',
    'ReferralEligibilityResponse',
    # Internal endpoints - Health/Access
    'HelloResponse',
    'ModelAccessResponse',
    # Statsig
    'StatsigUser',
    'StatsigCustomIDs',
    'StatsigCustom',
    'StatsigEnvironment',
    'StatsigMetadata',
    'StatsigInitializeRequest',
    'StatsigInitializeResponse',
    'StatsigInitializeFullBody',
    'StatsigEvent',
    'StatsigEventMetadata',
    'StatsigRegisterRequest',
    'StatsigRegisterResponse',
]
