#!/usr/bin/env -S uv run --quiet --no-project --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Deterministic gather for the `where-am-i` quest-map.

Resolves the session transcript (a session-id prefix, or — with no arg — the most
recently active one), then writes the three inputs the map-building agent reads:

    {session-dir}/where-am-i/spine.txt   the user's verbatim messages, in order — the intent spine
    {session-dir}/where-am-i/truth.txt   merged/open PRs, recent commits, worktrees — ground truth
    {session-dir}/where-am-i/meta.txt    compactions, subagents launched, most-used skills

Prints the paths + headline stats and the `top.md` path the skill writes the map to.
Why a spine: the user's own messages are the load-bearing signal of intent; a model summary
rounds off their exact corrections, the transcript does not.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

PROJECTS = Path.home() / '.claude' / 'projects'
# user-role messages that are injected noise, not directives — dropped from the spine
SKIP = (
    'This session is being continued from a previous',
    'Base directory for this skill',
    'Caveat: The messages below were generated by the user while running local commands',
)


def main() -> None:
    transcript = _resolve(sys.argv[1] if len(sys.argv) > 1 else None)
    out = transcript.with_suffix('') / 'where-am-i'
    out.mkdir(parents=True, exist_ok=True)

    n_msgs = _write_spine(transcript, out / 'spine.txt')
    _write_truth(out / 'truth.txt')
    headline = _write_meta(transcript, out / 'meta.txt')

    print(f'session:    {transcript.stem}')
    print(f'spine:      {out / "spine.txt"}   ({n_msgs} user messages)')
    print(f'truth:      {out / "truth.txt"}')
    print(f'meta:       {out / "meta.txt"}   ({headline})')
    print(f'WRITE MAP:  {out / "top.md"}   (per-node detail later under {out / "nodes"}/)')


def _resolve(arg: str | None) -> Path:
    if arg:
        matches = sorted(PROJECTS.glob(f'*/{arg}*.jsonl'))
        if not matches:
            sys.exit(f'no transcript found for session {arg!r} under {PROJECTS}')
        return matches[0]
    candidates = [p for d in PROJECTS.iterdir() if d.is_dir() for p in d.glob('*.jsonl')]
    if not candidates:
        sys.exit(f'no transcripts found under {PROJECTS}')
    return max(candidates, key=lambda p: p.stat().st_mtime)  # the actively-written one = current session


def _records(path: Path):
    with path.open(errors='ignore') as handle:
        for line in handle:
            try:
                yield json.loads(line)
            except json.JSONDecodeError:
                continue


def _write_spine(transcript: Path, dst: Path) -> int:
    out: list[str] = []
    n = 0
    for record in _records(transcript):
        if record.get('type') != 'user' or record.get('isMeta'):
            continue
        content = record.get('message', {}).get('content')
        if isinstance(content, str):
            text = content
        elif isinstance(content, list):
            text = '\n'.join(b.get('text', '') for b in content if isinstance(b, dict) and b.get('type') == 'text')
        else:
            continue
        text = text.strip()
        if not text or any(s in text[:120] for s in SKIP):
            continue
        n += 1
        timestamp = record.get('timestamp', '')
        out.append(f'[{n}] {timestamp}\n{text if len(text) <= 1400 else text[:1400] + " …[trunc]"}\n')
    dst.write_text('\n'.join(out))
    return n


def _write_truth(dst: Path) -> None:
    def sh(cmd: str) -> str:
        return subprocess.run(cmd, shell=True, capture_output=True, text=True, check=False).stdout

    blocks = [
        '## MERGED PRs',
        sh('gh pr list --state merged --limit 40 --json number,title --jq \'.[]|"#\\(.number) \\(.title)"\''),
        '\n## OPEN PRs',
        sh('gh pr list --state open --json number,title --jq \'.[]|"#\\(.number) \\(.title)"\''),
        '\n## recent origin/main',
        sh('git log --oneline -20 origin/main'),
        '\n## worktrees',
        sh('git worktree list'),
    ]
    dst.write_text('\n'.join(blocks))


def _write_meta(transcript: Path, dst: Path) -> str:
    compactions = 0
    skills: dict[str, int] = {}
    for record in _records(transcript):
        if record.get('type') != 'user':
            continue
        content = record.get('message', {}).get('content')
        if isinstance(content, str):
            text = content
        elif isinstance(content, list):
            text = ' '.join(b.get('text', '') for b in content if isinstance(b, dict) and b.get('type') == 'text')
        else:
            continue
        # skill SKILL.md injections arrive as isMeta=true user records — count them regardless of isMeta
        for match in re.finditer(r'Base directory for this skill: (\S+)', text):
            name = match.group(1).rsplit('/', 1)[-1].split('\\')[0]  # strip path + the trailing \n\n# artifact
            skills[name] = skills.get(name, 0) + 1
        # a real compaction summary is a NON-meta user message that starts with the marker
        if not record.get('isMeta') and text.lstrip().startswith('This session is being continued from a previous'):
            compactions += 1
    subagents = len(list((transcript.with_suffix('') / 'subagents').glob('agent-*.jsonl')))
    top = sorted(skills.items(), key=lambda kv: -kv[1])
    dst.write_text(
        f'compactions: {compactions}\n'
        f'subagents: {subagents}\n'
        f'skills (approx — re-injection inflates): {", ".join(f"{k} x{v}" for k, v in top[:8])}\n'
    )
    return f'{compactions} compactions · {subagents} subagents · top: {", ".join(k for k, _ in top[:3])}'


if __name__ == '__main__':
    main()
