#!/usr/bin/env -S uv run --quiet --no-project --script
# /// script
# requires-python = ">=3.13"
# dependencies = []
# ///
"""Deterministic gather for the where-am-i quest-map: the user-intent spine, the gh ground truth, and session metadata.

The spine is the user's verbatim messages — the load-bearing signal of intent a summary rounds off.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

PACIFIC = ZoneInfo('America/Los_Angeles')
PROJECTS = Path.home() / '.claude' / 'projects'
# user-role messages that are injected noise, not directives — dropped from the spine
SKIP = (
    'This session is being continued from a previous',
    'Base directory for this skill',
    'Caveat: The messages below were generated by the user while running local commands',
)


def main() -> None:
    transcript = _resolve(sys.argv[1] if len(sys.argv) > 1 else None)
    out = transcript.with_suffix('') / 'where-am-i'
    out.mkdir(parents=True, exist_ok=True)
    since = _session_start(transcript)

    n_msgs = _write_spine(transcript, out / 'user-intent-spine.txt')
    _write_truth(out / 'gh-ground-truth.txt', since)
    headline = _write_meta(transcript, out / 'session-metadata.txt')

    print(f'session:    {transcript.stem}')
    print(f'spine:      {out / "user-intent-spine.txt"}   ({n_msgs} user messages)')
    print(f'truth:      {out / "gh-ground-truth.txt"}   (PRs merged since {since})')
    print(f'meta:       {out / "session-metadata.txt"}   ({headline})')
    print(f'OUTPUT DIR: {out}')
    print('  the build workflow takes this dir as gatherDir and writes quest-map.md + nodes/ here')


def _resolve(arg: str | None) -> Path:
    if arg:
        matches = sorted(PROJECTS.glob(f'*/{arg}*.jsonl'))
        if not matches:
            sys.exit(f'no transcript found for session {arg!r} under {PROJECTS}')
        return matches[0]
    candidates = [p for d in PROJECTS.iterdir() if d.is_dir() for p in d.glob('*.jsonl')]
    if not candidates:
        sys.exit(f'no transcripts found under {PROJECTS}')
    return max(candidates, key=lambda p: p.stat().st_mtime)  # the actively-written one = current session


def _session_start(transcript: Path) -> str:
    """The earliest transcript timestamp as a Pacific YYYY-MM-DD — the lower bound for the PR window."""
    for record in _records(transcript):
        raw = record.get('timestamp', '')
        if raw:
            return f'{datetime.fromisoformat(raw).astimezone(PACIFIC):%Y-%m-%d}'
    sys.exit('could not determine session start: no timestamps in transcript')


def _records(path: Path):
    with path.open(errors='ignore') as handle:
        for line in handle:
            try:
                yield json.loads(line)
            except json.JSONDecodeError:
                continue


def _write_spine(transcript: Path, dst: Path) -> int:
    out: list[str] = []
    n = 0
    for record in _records(transcript):
        if record.get('type') != 'user' or record.get('isMeta'):
            continue
        content = record.get('message', {}).get('content')
        if isinstance(content, str):
            text = content
        elif isinstance(content, list):
            text = '\n'.join(b.get('text', '') for b in content if isinstance(b, dict) and b.get('type') == 'text')
        else:
            continue
        text = text.strip()
        if not text or any(s in text[:120] for s in SKIP):
            continue
        n += 1
        # transcript timestamps are UTC ISO; convert once here so no downstream consumer renders a UTC slip
        raw = record.get('timestamp', '')
        timestamp = f'{datetime.fromisoformat(raw).astimezone(PACIFIC):%Y-%m-%d %I:%M%p} PT' if raw else ''
        out.append(f'[{n}] {timestamp}\n{text if len(text) <= 1400 else text[:1400] + " …[trunc]"}\n')
    dst.write_text('\n'.join(out))
    return n


def _write_truth(dst: Path, since: str) -> None:
    """The git/GitHub ground truth, with merged PRs windowed to the session span.

    Windowing to `merged:>=since` makes the bound the session's own span, not an arbitrary count; a fetch
    that hits the cap fails loud rather than silently truncating — the failure mode that once mislabeled
    older roots when --limit cut them off.
    """
    cap = 500  # safety backstop well above one session's PR count — the guard below makes a hit loud, not silent

    def sh(cmd: str) -> str:
        return subprocess.run(cmd, shell=True, capture_output=True, text=True, check=True).stdout

    merged = json.loads(
        sh(f'gh pr list --search "is:merged merged:>={since}" --limit {cap} --json number,title,mergedAt')
    )
    if len(merged) >= cap:
        sys.exit(f'ground truth truncated: gh returned {len(merged)} merged PRs at the --limit {cap} cap — raise it')
    merged_lines = '\n'.join(f'#{pr["number"]} [{pr["mergedAt"][:10]}] {pr["title"]}' for pr in merged)

    blocks = [
        f'## MERGED PRs (session window — merged since {since})',
        merged_lines,
        '\n## OPEN PRs',
        sh('gh pr list --state open --limit 200 --json number,title --jq \'.[]|"#\\(.number) \\(.title)"\''),
        '\n## recent origin/main',
        sh('git log --oneline -20 origin/main'),
        '\n## worktrees',
        sh('git worktree list'),
    ]
    dst.write_text('\n'.join(blocks))


def _write_meta(transcript: Path, dst: Path) -> str:
    compactions = 0
    skills: dict[str, int] = {}
    for record in _records(transcript):
        if record.get('type') != 'user':
            continue
        content = record.get('message', {}).get('content')
        if isinstance(content, str):
            text = content
        elif isinstance(content, list):
            text = ' '.join(b.get('text', '') for b in content if isinstance(b, dict) and b.get('type') == 'text')
        else:
            continue
        # skill SKILL.md injections arrive as isMeta=true user records — count them regardless of isMeta
        for match in re.finditer(r'Base directory for this skill: (\S+)', text):
            name = match.group(1).rsplit('/', 1)[-1].split('\\')[0]  # strip path + the trailing \n\n# artifact
            skills[name] = skills.get(name, 0) + 1
        # a real compaction summary is a NON-meta user message that starts with the marker
        if not record.get('isMeta') and text.lstrip().startswith('This session is being continued from a previous'):
            compactions += 1
    subagents = len(list((transcript.with_suffix('') / 'subagents').glob('agent-*.jsonl')))
    top = sorted(skills.items(), key=lambda kv: -kv[1])
    dst.write_text(
        f'compactions: {compactions}\n'
        f'subagents: {subagents}\n'
        f'skills (approx — re-injection inflates): {", ".join(f"{k} x{v}" for k, v in top[:8])}\n'
    )
    return f'{compactions} compactions · {subagents} subagents · top: {", ".join(k for k, _ in top[:3])}'


if __name__ == '__main__':
    main()
