"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from grok_kit_sdk.utils.dynamic_imports import lazy_dir, lazy_getattr

from .grokkiterror import GrokKitError

if TYPE_CHECKING:
    from .grokkitdefaulterror import GrokKitDefaultError
    from .no_response_error import NoResponseError
    from .responsevalidationerror import ResponseValidationError

__all__ = [
    'GrokKitDefaultError',
    'GrokKitError',
    'NoResponseError',
    'ResponseValidationError',
]

_dynamic_imports: dict[str, str] = {
    'GrokKitDefaultError': '.grokkitdefaulterror',
    'NoResponseError': '.no_response_error',
    'ResponseValidationError': '.responsevalidationerror',
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(attr_name, package=__package__, dynamic_imports=_dynamic_imports)


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
