"""
Custom title handling for clone/restore operations.

Handles:
- Custom title extraction from session records
- Base title extraction (stripping clone suffix)
- Clone title generation with provenance

Custom title naming follows a similar pattern to slugs:
- Native: "My Session Name"
- Cloned: "My Session Name (clone-XXXXXXXX)" (8-char session prefix)

When cloning a clone, we extract the base title first to avoid accumulation:
- "Auth Feature (clone-019b5227)" → "Auth Feature (clone-019b53d9)"
  (NOT "Auth Feature (clone-019b5227) (clone-019b53d9)")
"""

from __future__ import annotations

import json
import re
import subprocess
from collections.abc import Mapping, Sequence
from pathlib import Path

from claude_session.schemas.session import AiTitleRecord, CustomTitleRecord, SessionRecord

__all__ = [
    'CLONE_SUFFIX_PATTERN',
    'extract_base_custom_title',
    'extract_custom_title_from_file',
    'extract_custom_title_from_records',
    'generate_clone_custom_title',
]


# Regex to match clone suffix: " (clone-XXXXXXXX)" where X is hex char
CLONE_SUFFIX_PATTERN = re.compile(r'\s*\(clone-[0-9a-fA-F]{8}\)$')


def extract_custom_title_from_records(files_data: Mapping[str, Sequence[SessionRecord]]) -> str | None:
    """
    Extract the displayable session title from records.

    Returns the latest ``CustomTitleRecord`` (user-set via ``/rename``) if
    any exists; otherwise returns the latest ``AiTitleRecord``
    (auto-generated, Claude Code 2.1.122+). Custom titles always take
    precedence regardless of which record came last in the file — matches
    Claude Code's own resume picker, which resolves both record types
    independently and prefers customTitle. Required because the
    ``generateSessionTitle`` SDK control request can append a fresh
    ``ai-title`` AFTER the user has run ``/rename``; a position-based
    latest-wins would incorrectly return the AI title in that case.

    Session files are append-only, so multiple entries of either type can
    exist (re-renames, re-runs of auto-titling); within each type the
    last-written value wins.

    Note: Assumes title records only appear in the main session file
    (titles are not agent operations). If multiple files contain title
    records, the 'last' is determined by dict iteration order which may
    not be chronological across files.

    Args:
        files_data: Mapping of filename -> sequence of SessionRecord

    Returns:
        The session title string, or None if no title record found
    """
    custom_title: str | None = None
    ai_title: str | None = None
    for records in files_data.values():
        for record in records:
            if isinstance(record, CustomTitleRecord):
                custom_title = record.customTitle
            elif isinstance(record, AiTitleRecord):
                ai_title = record.aiTitle
    return custom_title or ai_title


def extract_base_custom_title(title: str) -> str:
    """
    Extract the base title, removing any (clone-XXXXXXXX) suffix.

    For native titles, returns the title unchanged.
    For cloned titles, returns the portion before the clone suffix.

    Examples:
        'Auth Feature' -> 'Auth Feature'
        'Auth Feature (clone-019b5227)' -> 'Auth Feature'

    This enables flat cloning: cloning a clone produces the same
    format as cloning a native session, just with a different suffix.

    Args:
        title: Custom title string (native or cloned format)

    Returns:
        Base title without any clone suffix
    """
    return CLONE_SUFFIX_PATTERN.sub('', title)


def generate_clone_custom_title(original_title: str, new_session_id: str) -> str:
    """
    Generate new custom title with provenance.

    Format: {base_title} (clone-{session_prefix})
    Example: "Auth Feature (clone-019b51bd)"

    When cloning a clone, we extract the base title first to keep
    the naming flat rather than accumulating suffixes.

    Args:
        original_title: Original custom title string (may already be cloned)
        new_session_id: New session ID for the clone

    Returns:
        New custom title string showing provenance
    """
    base_title = extract_base_custom_title(original_title)
    prefix = new_session_id[:8]
    return f'{base_title} (clone-{prefix})'


def extract_custom_title_from_file(session_file: Path) -> str | None:
    """
    Extract the displayable session title from a JSONL file efficiently.

    Uses ripgrep to find title records (``custom-title`` set via ``/rename``
    or ``ai-title`` auto-generated by Claude Code 2.1.122+) without parsing
    the entire file. Custom titles always take precedence regardless of
    file position — matches Claude Code's own resume picker, which resolves
    both record types independently and prefers customTitle. Required
    because the ``generateSessionTitle`` SDK control request can append a
    fresh ``ai-title`` AFTER the user has run ``/rename``; a position-based
    latest-wins would incorrectly return the AI title in that case.

    Args:
        session_file: Path to the session JSONL file

    Returns:
        The session title string, or None if no title record found
    """
    if not session_file.exists():
        return None

    # Use rg to find lines containing title records (custom or AI-generated)
    result = subprocess.run(
        ['rg', '--no-filename', '-e', '"type":"custom-title"', '-e', '"type":"ai-title"', str(session_file)],
        check=False,
        capture_output=True,
        text=True,
    )

    if not result.stdout.strip():
        return None

    # Track latest of each type separately; custom wins regardless of position
    custom_title: str | None = None
    ai_title: str | None = None
    for line in result.stdout.strip().split('\n'):
        record = json.loads(line)
        record_type = record.get('type')
        if record_type == 'custom-title':
            custom_title = record.get('customTitle')
        elif record_type == 'ai-title':
            ai_title = record.get('aiTitle')

    return custom_title or ai_title
