"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Any, TypeVar, overload

import httpx

from grok_kit_sdk import errors

from .serializers import unmarshal_json

T = TypeVar('T')


@overload
def unmarshal_json_response(typ: type[T], http_res: httpx.Response, body: str | None = None) -> T: ...


@overload
def unmarshal_json_response(typ: Any, http_res: httpx.Response, body: str | None = None) -> Any: ...


def unmarshal_json_response(typ: Any, http_res: httpx.Response, body: str | None = None) -> Any:
    if body is None:
        body = http_res.text
    try:
        return unmarshal_json(body, typ)
    except Exception as e:
        raise errors.ResponseValidationError(
            'Response validation failed',
            http_res,
            e,
            body,
        ) from e
