"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from grok_kit_sdk.utils.dynamic_imports import lazy_dir, lazy_getattr

if TYPE_CHECKING:
    from .conversationdetailresponse import (
        ConversationDetailResponse,
        ConversationDetailResponseTypedDict,
    )
    from .conversationlistresponse import (
        ConversationListResponse,
        ConversationListResponseTypedDict,
    )
    from .conversationsummary import ConversationSummary, ConversationSummaryTypedDict
    from .getconversationop import (
        GetConversationRequest,
        GetConversationRequestTypedDict,
    )
    from .getresponsetreeop import (
        GetResponseTreeRequest,
        GetResponseTreeRequestTypedDict,
    )
    from .listconversationsop import (
        ListConversationsRequest,
        ListConversationsRequestTypedDict,
    )
    from .listsharelinksop import ListShareLinksRequest, ListShareLinksRequestTypedDict
    from .loadmessagesop import LoadMessagesRequest, LoadMessagesRequestTypedDict
    from .loadresponsesrequest import (
        LoadResponsesRequest,
        LoadResponsesRequestTypedDict,
    )
    from .loadresponsesresponse import (
        LoadResponsesResponse,
        LoadResponsesResponseTypedDict,
    )
    from .mediatype import MediaType
    from .messagebody import MessageBody, MessageBodyTypedDict
    from .messagesender import MessageSender
    from .responsenode import ResponseNode, ResponseNodeTypedDict
    from .responsetreeresponse import (
        ResponseTreeResponse,
        ResponseTreeResponseTypedDict,
    )
    from .security import Security, SecurityTypedDict
    from .sharelinksresponse import ShareLinksResponse, ShareLinksResponseTypedDict

__all__ = [
    'ConversationDetailResponse',
    'ConversationDetailResponseTypedDict',
    'ConversationListResponse',
    'ConversationListResponseTypedDict',
    'ConversationSummary',
    'ConversationSummaryTypedDict',
    'GetConversationRequest',
    'GetConversationRequestTypedDict',
    'GetResponseTreeRequest',
    'GetResponseTreeRequestTypedDict',
    'ListConversationsRequest',
    'ListConversationsRequestTypedDict',
    'ListShareLinksRequest',
    'ListShareLinksRequestTypedDict',
    'LoadMessagesRequest',
    'LoadMessagesRequestTypedDict',
    'LoadResponsesRequest',
    'LoadResponsesRequestTypedDict',
    'LoadResponsesResponse',
    'LoadResponsesResponseTypedDict',
    'MediaType',
    'MessageBody',
    'MessageBodyTypedDict',
    'MessageSender',
    'ResponseNode',
    'ResponseNodeTypedDict',
    'ResponseTreeResponse',
    'ResponseTreeResponseTypedDict',
    'Security',
    'SecurityTypedDict',
    'ShareLinksResponse',
    'ShareLinksResponseTypedDict',
]

_dynamic_imports: dict[str, str] = {
    'ConversationDetailResponse': '.conversationdetailresponse',
    'ConversationDetailResponseTypedDict': '.conversationdetailresponse',
    'ConversationListResponse': '.conversationlistresponse',
    'ConversationListResponseTypedDict': '.conversationlistresponse',
    'ConversationSummary': '.conversationsummary',
    'ConversationSummaryTypedDict': '.conversationsummary',
    'GetConversationRequest': '.getconversationop',
    'GetConversationRequestTypedDict': '.getconversationop',
    'GetResponseTreeRequest': '.getresponsetreeop',
    'GetResponseTreeRequestTypedDict': '.getresponsetreeop',
    'ListConversationsRequest': '.listconversationsop',
    'ListConversationsRequestTypedDict': '.listconversationsop',
    'ListShareLinksRequest': '.listsharelinksop',
    'ListShareLinksRequestTypedDict': '.listsharelinksop',
    'LoadMessagesRequest': '.loadmessagesop',
    'LoadMessagesRequestTypedDict': '.loadmessagesop',
    'LoadResponsesRequest': '.loadresponsesrequest',
    'LoadResponsesRequestTypedDict': '.loadresponsesrequest',
    'LoadResponsesResponse': '.loadresponsesresponse',
    'LoadResponsesResponseTypedDict': '.loadresponsesresponse',
    'MediaType': '.mediatype',
    'MessageBody': '.messagebody',
    'MessageBodyTypedDict': '.messagebody',
    'MessageSender': '.messagesender',
    'ResponseNode': '.responsenode',
    'ResponseNodeTypedDict': '.responsenode',
    'ResponseTreeResponse': '.responsetreeresponse',
    'ResponseTreeResponseTypedDict': '.responsetreeresponse',
    'Security': '.security',
    'SecurityTypedDict': '.security',
    'ShareLinksResponse': '.sharelinksresponse',
    'ShareLinksResponseTypedDict': '.sharelinksresponse',
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(attr_name, package=__package__, dynamic_imports=_dynamic_imports)


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
