"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing_extensions import TypedDict

from grok_kit_sdk.types import BaseModel

from .conversationsummary import ConversationSummary, ConversationSummaryTypedDict


class ConversationDetailResponseTypedDict(TypedDict):
    conversation: ConversationSummaryTypedDict


class ConversationDetailResponse(BaseModel):
    conversation: ConversationSummary
