"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, Any, NotRequired

import pydantic
from pydantic import model_serializer
from typing_extensions import TypedDict

from grok_kit_sdk.types import UNSET_SENTINEL, BaseModel

from .conversationsummary import ConversationSummary, ConversationSummaryTypedDict


class ConversationListResponseTypedDict(TypedDict):
    conversations: list[ConversationSummaryTypedDict]
    next_page_token: NotRequired[str]
    r"""Page cursor; empty string when last page."""
    text_search_matches: NotRequired[list[dict[str, Any]]]
    r"""Text-search match metadata; observed empty when no query."""


class ConversationListResponse(BaseModel):
    conversations: list[ConversationSummary]

    next_page_token: Annotated[str | None, pydantic.Field(alias='nextPageToken')] = None
    r"""Page cursor; empty string when last page."""

    text_search_matches: Annotated[list[dict[str, Any]] | None, pydantic.Field(alias='textSearchMatches')] = None
    r"""Text-search match metadata; observed empty when no query."""

    @model_serializer(mode='wrap')
    def serialize_model(self, handler):
        optional_fields = set(['nextPageToken', 'textSearchMatches'])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    ConversationListResponse.model_rebuild()
except NameError:
    pass
