"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Any

import pydantic
from typing_extensions import TypedDict

from grok_kit_sdk.types import BaseModel

from .mediatype import MediaType


class ConversationSummaryTypedDict(TypedDict):
    conversation_id: str
    title: str
    starred: bool
    create_time: datetime
    modify_time: datetime
    system_prompt_name: str
    r"""Name of the system prompt used; empty string when default."""
    temporary: bool
    r"""True for \"incognito\"/private chats not persisted to history."""
    media_types: list[MediaType]
    workspaces: list[dict[str, Any]]
    r"""Workspace memberships; observed empty in personal-tier accounts."""
    task_result: dict[str, Any]
    r"""Result payload for tasks; observed empty for chat conversations."""


class ConversationSummary(BaseModel):
    conversation_id: Annotated[str, pydantic.Field(alias='conversationId')]

    title: str

    starred: bool

    create_time: Annotated[datetime, pydantic.Field(alias='createTime')]

    modify_time: Annotated[datetime, pydantic.Field(alias='modifyTime')]

    system_prompt_name: Annotated[str, pydantic.Field(alias='systemPromptName')]
    r"""Name of the system prompt used; empty string when default."""

    temporary: bool
    r"""True for \"incognito\"/private chats not persisted to history."""

    media_types: Annotated[list[MediaType], pydantic.Field(alias='mediaTypes')]

    workspaces: list[dict[str, Any]]
    r"""Workspace memberships; observed empty in personal-tier accounts."""

    task_result: Annotated[dict[str, Any], pydantic.Field(alias='taskResult')]
    r"""Result payload for tasks; observed empty for chat conversations."""


try:
    ConversationSummary.model_rebuild()
except NameError:
    pass
