"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, NotRequired

import pydantic
from pydantic import model_serializer
from typing_extensions import TypedDict

from grok_kit_sdk.types import UNSET_SENTINEL, BaseModel
from grok_kit_sdk.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata


class GetConversationRequestTypedDict(TypedDict):
    conversation_id: str
    include_workspaces: NotRequired[bool]
    include_task_result: NotRequired[bool]


class GetConversationRequest(BaseModel):
    conversation_id: Annotated[
        str,
        pydantic.Field(alias='conversationId'),
        FieldMetadata(path=PathParamMetadata(style='simple', explode=False)),
    ]

    include_workspaces: Annotated[
        bool | None,
        pydantic.Field(alias='includeWorkspaces'),
        FieldMetadata(query=QueryParamMetadata(style='form', explode=True)),
    ] = True

    include_task_result: Annotated[
        bool | None,
        pydantic.Field(alias='includeTaskResult'),
        FieldMetadata(query=QueryParamMetadata(style='form', explode=True)),
    ] = True

    @model_serializer(mode='wrap')
    def serialize_model(self, handler):
        optional_fields = set(['includeWorkspaces', 'includeTaskResult'])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
