"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, NotRequired

import pydantic
from pydantic import model_serializer
from typing_extensions import TypedDict

from grok_kit_sdk.types import UNSET_SENTINEL, BaseModel
from grok_kit_sdk.utils import FieldMetadata, QueryParamMetadata


class ListConversationsRequestTypedDict(TypedDict):
    page_size: NotRequired[int]
    r"""Server caps observed at 60."""
    page_token: NotRequired[str]
    r"""Cursor from a prior response's `nextPageToken`."""
    filter_is_starred: NotRequired[bool]
    r"""Restrict to starred conversations only."""


class ListConversationsRequest(BaseModel):
    page_size: Annotated[
        int | None,
        pydantic.Field(alias='pageSize'),
        FieldMetadata(query=QueryParamMetadata(style='form', explode=True)),
    ] = 60
    r"""Server caps observed at 60."""

    page_token: Annotated[
        str | None,
        pydantic.Field(alias='pageToken'),
        FieldMetadata(query=QueryParamMetadata(style='form', explode=True)),
    ] = None
    r"""Cursor from a prior response's `nextPageToken`."""

    filter_is_starred: Annotated[
        bool | None,
        pydantic.Field(alias='filterIsStarred'),
        FieldMetadata(query=QueryParamMetadata(style='form', explode=True)),
    ] = None
    r"""Restrict to starred conversations only."""

    @model_serializer(mode='wrap')
    def serialize_model(self, handler):
        optional_fields = set(['pageSize', 'pageToken', 'filterIsStarred'])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
