"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, NotRequired

import pydantic
from pydantic import model_serializer
from typing_extensions import TypedDict

from grok_kit_sdk.types import UNSET_SENTINEL, BaseModel
from grok_kit_sdk.utils import FieldMetadata, QueryParamMetadata


class ListShareLinksRequestTypedDict(TypedDict):
    conversation_id: str
    page_size: NotRequired[int]


class ListShareLinksRequest(BaseModel):
    conversation_id: Annotated[
        str,
        pydantic.Field(alias='conversationId'),
        FieldMetadata(query=QueryParamMetadata(style='form', explode=True)),
    ]

    page_size: Annotated[
        int | None,
        pydantic.Field(alias='pageSize'),
        FieldMetadata(query=QueryParamMetadata(style='form', explode=True)),
    ] = 100

    @model_serializer(mode='wrap')
    def serialize_model(self, handler):
        optional_fields = set(['pageSize'])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
