"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated

import pydantic
from typing_extensions import TypedDict

from grok_kit_sdk.types import BaseModel
from grok_kit_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata

from .loadresponsesrequest import LoadResponsesRequest, LoadResponsesRequestTypedDict


class LoadMessagesRequestTypedDict(TypedDict):
    conversation_id: str
    body: LoadResponsesRequestTypedDict


class LoadMessagesRequest(BaseModel):
    conversation_id: Annotated[
        str,
        pydantic.Field(alias='conversationId'),
        FieldMetadata(path=PathParamMetadata(style='simple', explode=False)),
    ]

    body: Annotated[
        LoadResponsesRequest,
        FieldMetadata(request=RequestMetadata(media_type='application/json')),
    ]
