"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated

import pydantic
from typing_extensions import TypedDict

from grok_kit_sdk.types import BaseModel


class LoadResponsesRequestTypedDict(TypedDict):
    response_ids: list[str]


class LoadResponsesRequest(BaseModel):
    response_ids: Annotated[list[str], pydantic.Field(alias='responseIds')]


try:
    LoadResponsesRequest.model_rebuild()
except NameError:
    pass
