"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Literal, Union

from grok_kit_sdk.types import UnrecognizedStr

MediaType = Union[
    Literal[
        'audio',
        'text',
        'image',
        'video',
    ],
    UnrecognizedStr,
]
r"""Media type tags on a conversation. Observed values; xAI may add more."""
