"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Literal, Union

from grok_kit_sdk.types import UnrecognizedStr

MessageSender = Union[
    Literal[
        'human',
        'assistant',
    ],
    UnrecognizedStr,
]
r"""Originator of a message."""
