"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Any, NotRequired

import pydantic
from pydantic import model_serializer
from typing_extensions import TypedDict

from grok_kit_sdk.types import UNSET_SENTINEL, BaseModel

from .mediatype import MediaType
from .messagesender import MessageSender


class MessageBodyTypedDict(TypedDict):
    response_id: str
    message: str
    r"""Full message text. Empty string allowed."""
    sender: MessageSender
    r"""Originator of a message."""
    create_time: datetime
    manual: bool
    partial: bool
    shared: bool
    parent_response_id: NotRequired[str]
    query: NotRequired[str]
    query_type: NotRequired[str]
    model: NotRequired[str]
    media_types: NotRequired[list[MediaType]]
    web_search_results: NotRequired[list[dict[str, Any]]]
    xpost_ids: NotRequired[list[str]]
    xposts: NotRequired[list[dict[str, Any]]]
    generated_image_urls: NotRequired[list[str]]
    image_attachments: NotRequired[list[dict[str, Any]]]
    file_attachments: NotRequired[list[dict[str, Any]]]
    card_attachments_json: NotRequired[list[dict[str, Any]]]
    file_uris: NotRequired[list[str]]
    file_attachments_metadata: NotRequired[list[dict[str, Any]]]
    is_control: NotRequired[bool]
    steps: NotRequired[list[dict[str, Any]]]
    image_edit_uris: NotRequired[list[str]]
    webpage_urls: NotRequired[list[str]]
    metadata: NotRequired[dict[str, Any]]
    cited_web_search_results: NotRequired[list[dict[str, Any]]]
    tool_responses: NotRequired[list[dict[str, Any]]]
    rag_results: NotRequired[list[dict[str, Any]]]
    cited_rag_results: NotRequired[list[dict[str, Any]]]
    search_product_results: NotRequired[list[dict[str, Any]]]
    connector_search_results: NotRequired[list[dict[str, Any]]]
    collection_search_results: NotRequired[list[dict[str, Any]]]
    stream_errors: NotRequired[list[dict[str, Any]]]
    cited_xposts: NotRequired[list[dict[str, Any]]]
    cited_connector_search_results: NotRequired[list[dict[str, Any]]]
    cited_collection_search_results: NotRequired[list[dict[str, Any]]]


class MessageBody(BaseModel):
    response_id: Annotated[str, pydantic.Field(alias='responseId')]

    message: str
    r"""Full message text. Empty string allowed."""

    sender: MessageSender
    r"""Originator of a message."""

    create_time: Annotated[datetime, pydantic.Field(alias='createTime')]

    manual: bool

    partial: bool

    shared: bool

    parent_response_id: Annotated[str | None, pydantic.Field(alias='parentResponseId')] = None

    query: str | None = None

    query_type: Annotated[str | None, pydantic.Field(alias='queryType')] = None

    model: str | None = None

    media_types: Annotated[list[MediaType] | None, pydantic.Field(alias='mediaTypes')] = None

    web_search_results: Annotated[list[dict[str, Any]] | None, pydantic.Field(alias='webSearchResults')] = None

    xpost_ids: Annotated[list[str] | None, pydantic.Field(alias='xpostIds')] = None

    xposts: list[dict[str, Any]] | None = None

    generated_image_urls: Annotated[list[str] | None, pydantic.Field(alias='generatedImageUrls')] = None

    image_attachments: Annotated[list[dict[str, Any]] | None, pydantic.Field(alias='imageAttachments')] = None

    file_attachments: Annotated[list[dict[str, Any]] | None, pydantic.Field(alias='fileAttachments')] = None

    card_attachments_json: Annotated[list[dict[str, Any]] | None, pydantic.Field(alias='cardAttachmentsJson')] = None

    file_uris: Annotated[list[str] | None, pydantic.Field(alias='fileUris')] = None

    file_attachments_metadata: Annotated[
        list[dict[str, Any]] | None, pydantic.Field(alias='fileAttachmentsMetadata')
    ] = None

    is_control: Annotated[bool | None, pydantic.Field(alias='isControl')] = None

    steps: list[dict[str, Any]] | None = None

    image_edit_uris: Annotated[list[str] | None, pydantic.Field(alias='imageEditUris')] = None

    webpage_urls: Annotated[list[str] | None, pydantic.Field(alias='webpageUrls')] = None

    metadata: dict[str, Any] | None = None

    cited_web_search_results: Annotated[list[dict[str, Any]] | None, pydantic.Field(alias='citedWebSearchResults')] = (
        None
    )

    tool_responses: Annotated[list[dict[str, Any]] | None, pydantic.Field(alias='toolResponses')] = None

    rag_results: Annotated[list[dict[str, Any]] | None, pydantic.Field(alias='ragResults')] = None

    cited_rag_results: Annotated[list[dict[str, Any]] | None, pydantic.Field(alias='citedRagResults')] = None

    search_product_results: Annotated[list[dict[str, Any]] | None, pydantic.Field(alias='searchProductResults')] = None

    connector_search_results: Annotated[list[dict[str, Any]] | None, pydantic.Field(alias='connectorSearchResults')] = (
        None
    )

    collection_search_results: Annotated[
        list[dict[str, Any]] | None, pydantic.Field(alias='collectionSearchResults')
    ] = None

    stream_errors: Annotated[list[dict[str, Any]] | None, pydantic.Field(alias='streamErrors')] = None

    cited_xposts: Annotated[list[dict[str, Any]] | None, pydantic.Field(alias='citedXposts')] = None

    cited_connector_search_results: Annotated[
        list[dict[str, Any]] | None,
        pydantic.Field(alias='citedConnectorSearchResults'),
    ] = None

    cited_collection_search_results: Annotated[
        list[dict[str, Any]] | None,
        pydantic.Field(alias='citedCollectionSearchResults'),
    ] = None

    @model_serializer(mode='wrap')
    def serialize_model(self, handler):
        optional_fields = set(
            [
                'parentResponseId',
                'query',
                'queryType',
                'model',
                'mediaTypes',
                'webSearchResults',
                'xpostIds',
                'xposts',
                'generatedImageUrls',
                'imageAttachments',
                'fileAttachments',
                'cardAttachmentsJson',
                'fileUris',
                'fileAttachmentsMetadata',
                'isControl',
                'steps',
                'imageEditUris',
                'webpageUrls',
                'metadata',
                'citedWebSearchResults',
                'toolResponses',
                'ragResults',
                'citedRagResults',
                'searchProductResults',
                'connectorSearchResults',
                'collectionSearchResults',
                'streamErrors',
                'citedXposts',
                'citedConnectorSearchResults',
                'citedCollectionSearchResults',
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    MessageBody.model_rebuild()
except NameError:
    pass
