"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, NotRequired

import pydantic
from pydantic import model_serializer
from typing_extensions import TypedDict

from grok_kit_sdk.types import UNSET_SENTINEL, BaseModel

from .messagesender import MessageSender


class ResponseNodeTypedDict(TypedDict):
    response_id: str
    sender: MessageSender
    r"""Originator of a message."""
    parent_response_id: NotRequired[str]
    r"""Parent message in the conversation tree; null/absent on root."""


class ResponseNode(BaseModel):
    response_id: Annotated[str, pydantic.Field(alias='responseId')]

    sender: MessageSender
    r"""Originator of a message."""

    parent_response_id: Annotated[str | None, pydantic.Field(alias='parentResponseId')] = None
    r"""Parent message in the conversation tree; null/absent on root."""

    @model_serializer(mode='wrap')
    def serialize_model(self, handler):
        optional_fields = set(['parentResponseId'])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    ResponseNode.model_rebuild()
except NameError:
    pass
