"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated

import pydantic
from typing_extensions import TypedDict

from grok_kit_sdk.types import BaseModel

from .responsenode import ResponseNode, ResponseNodeTypedDict


class ResponseTreeResponseTypedDict(TypedDict):
    response_nodes: list[ResponseNodeTypedDict]


class ResponseTreeResponse(BaseModel):
    response_nodes: Annotated[list[ResponseNode], pydantic.Field(alias='responseNodes')]


try:
    ResponseTreeResponse.model_rebuild()
except NameError:
    pass
