"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated

from typing_extensions import TypedDict

from grok_kit_sdk.types import BaseModel
from grok_kit_sdk.utils import FieldMetadata, SecurityMetadata


class SecurityTypedDict(TypedDict):
    cookie_header: str


class Security(BaseModel):
    cookie_header: Annotated[
        str,
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type='apiKey',
                sub_type='header',
                field_name='Cookie',
            )
        ),
    ]
