"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, Any

import pydantic
from typing_extensions import TypedDict

from grok_kit_sdk.types import BaseModel


class ShareLinksResponseTypedDict(TypedDict):
    share_links: list[dict[str, Any]]


class ShareLinksResponse(BaseModel):
    share_links: Annotated[list[dict[str, Any]], pydantic.Field(alias='shareLinks')]


try:
    ShareLinksResponse.model_rebuild()
except NameError:
    pass
