workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    grok-rest:
        inputs:
            - location: ../api-spec/openapi.yaml
targets:
    grok-kit-sdk:
        target: python
        source: grok-rest
