"""Type stubs for fitz (PyMuPDF).

These stubs supplement pymupdf-stubs with missing method signatures.
See: https://github.com/pymupdf/PyMuPDF/issues/3361
"""

from collections.abc import Iterator
from typing import Any, Literal, overload

# Re-export base types from pymupdf

class Rect:
    @property
    def height(self) -> float: ...
    @property
    def width(self) -> float: ...
    @property
    def x0(self) -> float: ...
    @property
    def y0(self) -> float: ...
    @property
    def x1(self) -> float: ...
    @property
    def y1(self) -> float: ...

class TextPage:
    def get_text(self) -> str: ...

class Page:
    @property
    def rect(self) -> Rect: ...
    @overload
    def get_text(self) -> str: ...
    @overload
    def get_text(self, option: Literal['text', 'html', 'xhtml', 'xml', 'json']) -> str: ...
    @overload
    def get_text(self, option: Literal['dict', 'rawdict', 'blocks', 'words']) -> dict[str, Any]: ...
    def get_textpage(self, **kwargs: Any) -> TextPage: ...
    def get_textpage_ocr(self, full: bool = False, **kwargs: Any) -> TextPage: ...
    def get_images(self, full: bool = False) -> list[tuple[int, ...]]: ...

class Document:
    @property
    def page_count(self) -> int: ...
    @property
    def name(self) -> str: ...
    def __getitem__(self, page_num: int) -> Page: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Page]: ...
    def __enter__(self) -> Document: ...
    def __exit__(self, *args: Any) -> None: ...
    def close(self) -> None: ...
    def get_toc(self, simple: bool = True) -> list[list[Any]]: ...

def open(
    filename: str | None = None,
    stream: bytes | None = None,
    filetype: str | None = None,
    **kwargs: Any,
) -> Document: ...
