"""Type stubs for redis.asyncio - async Redis client."""

import builtins
from collections.abc import AsyncIterator, Mapping, Sequence
from typing import Any

class ConnectionPool:
    def __init__(
        self,
        host: str = ...,
        port: int = ...,
        *,
        max_connections: int = ...,
        socket_timeout: float = ...,
        socket_connect_timeout: float = ...,
        decode_responses: bool = ...,
    ) -> None: ...

class Pipeline:
    def hgetall(self, name: str) -> Pipeline: ...
    def hget(self, name: str | bytes, key: str | bytes) -> Pipeline: ...
    def hmget(self, name: str | bytes, *keys: str | bytes) -> Pipeline: ...
    def delete(self, *names: str) -> Pipeline: ...
    def unlink(self, *names: str | bytes) -> Pipeline: ...
    def sadd(self, name: str | bytes, *values: str | bytes) -> Pipeline: ...
    def expire(self, name: str | bytes, time: int) -> Pipeline: ...
    def set(self, name: str, value: str | bytes, *, ex: int | None = ...) -> Pipeline: ...
    async def execute(self) -> list[Any]: ...

class Redis:
    def __init__(self, *, connection_pool: ConnectionPool) -> None: ...
    async def ping(self) -> bool: ...
    async def mget(self, keys: Sequence[str]) -> list[bytes | None]: ...
    async def set(self, name: str, value: str | bytes, *, ex: int | None = ...) -> bool | None: ...
    async def hset(self, name: str, *, mapping: Mapping[bytes, bytes]) -> int: ...
    async def hgetall(self, name: str) -> dict[bytes, bytes]: ...
    async def hget(self, name: str, key: str | bytes) -> bytes | None: ...
    async def delete(self, *names: str) -> int: ...
    async def unlink(self, *names: str | bytes) -> int: ...
    async def expire(self, name: str, time: int) -> bool: ...
    async def smembers(self, name: str) -> builtins.set[bytes]: ...
    def scan_iter(self, *, match: str, count: int = ...) -> AsyncIterator[bytes]: ...
    def pipeline(self, *, transaction: bool = ...) -> Pipeline: ...
    async def aclose(self) -> None: ...
