#!/usr/bin/env -S uv run --no-project --script
# /// script
# requires-python = ">=3.13"
# dependencies = [
#     "cc_lib",
#     "typer>=0.9.0",
# ]
#
# [tool.uv.sources]
# cc_lib = { path = "../cc-lib/", editable = true }
# ///

"""Make a project skill available at user scope, with the hoist owning dep resolution.

A skill stays naive: a normal SKILL.md whose ``!``-line invokes its companion script via
``${CLAUDE_SKILL_DIR}/<script>``, and a script that declares relative editable deps
(``cc-lib = { path = "../../cc-lib" }``). That works in-repo. A *bare symlink* into
``~/.claude/skills`` breaks it — uv resolves the relative deps from the symlink dir, and
CC's permission analyzer rejects a ``$(realpath …)`` workaround in the ``!``-line.

So ``hoist`` doesn't bare-symlink. It builds ``~/.claude/skills/<name>/`` as a real dir:

    SKILL.md           -> symlink to the repo (single source of truth)
    data / no-dep .py  -> symlink to the repo
    dep-bearing .py    -> a generated runner that execs the real repo script via uv

CC discovers the dir, ``${CLAUDE_SKILL_DIR}`` resolves to it (the binary doesn't realpath it),
and the ``!``-line lands on the generated runner, which re-runs the real script from the repo
so its relative deps resolve. The skill author never thinks about hoisting — the hoist owns
the workaround, in the layer that creates the problem.

    claude-hoist-skill hoist skills/recover-session   # build the structure
    claude-hoist-skill unhoist recover-session        # remove it (refuses real dirs we didn't make)
    claude-hoist-skill list                           # hoisted skills vs un-hoisted real dirs
    claude-hoist-skill install                        # put claude-hoist-skill on PATH
"""

from __future__ import annotations

import os
import re
import shutil
import sys
from collections.abc import Callable
from pathlib import Path

import typer
from cc_lib.cli import add_help_command, add_install_command, create_app, run_app
from cc_lib.error_boundary import ErrorBoundary
from cc_lib.utils import get_claude_config_home_dir


class HoistError(Exception):
    """An expected, actionable hoist failure — formatted at the boundary, not as a traceback."""


# Filesystem-safe skill name: leading alnum, then alnum / dot / dash / underscore.
SAFE_NAME = re.compile(r'^[A-Za-z0-9][A-Za-z0-9._-]*$')

# Emitted into ~/.claude/skills/<name>/<script> for each dep-bearing companion script: re-runs
# the real repo script so uv resolves its relative [tool.uv.sources] from the repo, not the
# hoisted dir — the workaround the analyzer won't accept inline in a !-line.
_RUNNER_TEMPLATE = """\
#!/usr/bin/env -S uv run --quiet --script
# /// script
# requires-python = ">=3.13"
# ///
# Generated by claude-hoist-skill: run {name} from its repo location so uv resolves its
# relative editable deps from the repo, not this hoisted ~/.claude dir. Re-emitted per hoist.
import os
import sys

os.execvp('uv', ['uv', 'run', '--quiet', '--script', {real}, *sys.argv[1:]])
"""

app = create_app(help='Hoist a project skill to user scope; the hoist owns dep resolution.')
add_help_command(app)
error_boundary = ErrorBoundary(exit_code=1)


@error_boundary.handler(HoistError)
def _on_hoist_error(exc: HoistError) -> None:
    """Print the actionable message (no traceback); the boundary then exits 1."""
    print(f'error: {exc}', file=sys.stderr)


@app.command()
@error_boundary
def hoist(
    skill_dir: str = typer.Argument(..., help='Project skill directory to hoist (must contain SKILL.md)'),
    name: str | None = typer.Option(None, '--name', help='User-scope name (default: the directory basename)'),
    dry_run: bool = typer.Option(False, '--dry-run', help='Print the action and touch nothing'),
) -> None:
    """Build ~/.claude/skills/<name>/ from a project skill; the repo stays the source of truth.

    Rebuilds idempotently over a prior hoist (a legacy bare symlink, or a generated structure).
    Fails loudly on a real directory we did not create.
    """
    src = Path(skill_dir).resolve()
    if not src.is_dir():
        raise HoistError(f'not a directory: {src}')
    if not (src / 'SKILL.md').is_file():
        raise HoistError(f'{src} is not a skill: no SKILL.md')

    skill_name = name or src.name
    if skill_name in ('.', '..') or not SAFE_NAME.match(skill_name):
        raise HoistError(f'unsafe skill name: {skill_name!r}')

    dst = get_claude_config_home_dir() / 'skills' / skill_name
    occupied = dst.is_symlink() or dst.exists()
    if occupied and not _is_our_hoist(dst):
        raise HoistError(f'{dst} is a real directory we did not create — refusing to replace it.')

    verb = 're-hoisted' if occupied else 'hoisted'
    _apply(dry_run, f'{verb} {dst} -> {src}', lambda: _rebuild(src, dst))


@app.command()
@error_boundary
def unhoist(
    name: str = typer.Argument(..., help='Skill name (or path) to remove from user scope'),
    dry_run: bool = typer.Option(False, '--dry-run', help='Print the action and touch nothing'),
) -> None:
    """Remove a hoisted skill. Refuses anything we did not create (a hand-authored real dir)."""
    dst = get_claude_config_home_dir() / 'skills' / Path(name).name
    if not (dst.is_symlink() or dst.exists()):
        print(f'not hoisted: {dst}')
        return
    if not _is_our_hoist(dst):
        raise HoistError(f'{dst} is a real directory we did not create — refusing to remove it.')
    _apply(dry_run, f'unhoisted {dst}', lambda: _remove_hoist(dst))


@app.command('list')
@error_boundary
def list_skills() -> None:
    """List user-scope skills: hoisted (-> repo) vs un-hoisted real dirs."""
    skills_dir = get_claude_config_home_dir() / 'skills'
    if not skills_dir.is_dir():
        print(f'no user-scope skills directory: {skills_dir}')
        return
    for entry in sorted(skills_dir.iterdir()):
        if entry.name.startswith('.'):
            continue
        if entry.is_symlink():  # legacy bare-symlink hoist
            target = _symlink_target(entry)
            flag = '' if target.exists() else '  [BROKEN]'
            print(f'{entry.name}  -> {target}  (legacy symlink){flag}')
        elif entry.is_dir() and (entry / 'SKILL.md').is_symlink():  # our generated structure
            print(f'{entry.name}  -> {_symlink_target(entry / "SKILL.md").parent}')
        elif entry.is_dir():
            print(f'{entry.name}  (real dir — not hoisted)')


# -- structure build / teardown ----------------------------------------------


def _rebuild(src: Path, dst: Path) -> None:
    """Tear down any prior hoist, then build the structure fresh (idempotent)."""
    if dst.is_symlink() or dst.exists():
        _remove_hoist(dst)
    dst.mkdir(parents=True)
    for entry in sorted(src.iterdir()):
        target = dst / entry.name
        if entry.suffix == '.py' and _has_relative_uv_deps(entry):
            _write_runner(target, entry)
        else:
            os.symlink(entry, target)


def _remove_hoist(dst: Path) -> None:
    """Remove our hoist — a legacy bare symlink, or a generated dir of symlinks + runners."""
    if dst.is_symlink():
        dst.unlink()
    else:
        shutil.rmtree(dst)


def _is_our_hoist(dst: Path) -> bool:
    """True if we created this: a legacy bare symlink, or a dir whose SKILL.md is a symlink."""
    if dst.is_symlink():
        return True
    return dst.is_dir() and (dst / 'SKILL.md').is_symlink()


def _has_relative_uv_deps(script: Path) -> bool:
    """True if a PEP 723 script declares a relative [tool.uv.sources] (breaks under a bare symlink)."""
    header = script.read_text(errors='replace')[:2000]
    return '[tool.uv.sources]' in header and '"../' in header


def _write_runner(target: Path, real_script: Path) -> None:
    """Emit a runner that execs the real repo script (so uv resolves its deps from the repo)."""
    target.write_text(_RUNNER_TEMPLATE.format(name=real_script.name, real=repr(str(real_script))))
    target.chmod(0o755)


def _symlink_target(link: Path) -> Path:
    """Resolve a symlink's stored target to an absolute path (handles relative links)."""
    raw = Path(os.readlink(link))
    return raw if raw.is_absolute() else (link.parent / raw).resolve()


def _apply(dry_run: bool, summary: str, action: Callable[[], None]) -> None:
    """Run ``action`` (unless dry-run) and print ``summary``."""
    if dry_run:
        print(f'[dry-run] {summary}')
        return
    action()
    print(summary)


add_install_command(app, script_path=__file__)


if __name__ == '__main__':
    run_app(app)
