#!/bin/sh
# install-launcher.sh — Install a uv script as a PATH-accessible command.
#
# Workaround: uv doesn't resolve symlinks before computing relative paths
# in [tool.uv.sources]. Symlinks from ~/.local/bin/ cause relative paths
# to resolve from the symlink's directory, not the script's real location.
#
# This replaces symlinks with launcher scripts that pass the resolved
# script path to `uv run --script`, so [tool.uv.sources] paths resolve
# correctly from the script's actual directory.
#
# Usage:
#   ./install-launcher.sh scripts/claude-login.py
#   ./install-launcher.sh scripts/claude-login.py my-custom-name
#
# The command name defaults to the script's basename minus .py extension.
# Tab completion works when the script normalizes sys.argv[0]:
#   sys.argv[0] = os.path.basename(sys.argv[0]).removesuffix('.py')

set -eu

if [ $# -lt 1 ]; then
    echo "Usage: $0 <script-path> [command-name]" >&2
    exit 1
fi

SCRIPT_PATH="$1"
COMMAND_NAME="${2:-$(basename "$SCRIPT_PATH" .py)}"
BIN_DIR="${HOME}/.local/bin"
LAUNCHER="${BIN_DIR}/${COMMAND_NAME}"

# Resolve to absolute path
REAL_PATH="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)/$(basename "$SCRIPT_PATH")"

if [ ! -f "$REAL_PATH" ]; then
    echo "Error: Script not found: $REAL_PATH" >&2
    exit 1
fi

# Detect and replace existing symlink (migration from old approach)
if [ -L "$LAUNCHER" ]; then
    echo "Replacing symlink: $LAUNCHER"
    rm "$LAUNCHER"
elif [ -f "$LAUNCHER" ]; then
    echo "Replacing existing launcher: $LAUNCHER"
fi

mkdir -p "$BIN_DIR"

# Generate launcher — passes all args through, preserves exit code
cat > "$LAUNCHER" << EOF
#!/bin/sh
# Launcher for ${COMMAND_NAME} — resolves real script path so uv's
# relative [tool.uv.sources] paths resolve from the script's directory.
# Generated by install-launcher.sh — do not edit manually.
exec uv run --no-project --script "${REAL_PATH}" "\$@"
EOF

chmod +x "$LAUNCHER"

echo "Installed: ${LAUNCHER}"
echo "  -> ${REAL_PATH}"