"""Type stubs for expiringdict.

Coverage: ExpiringDict class with generic key/value types.
See: https://github.com/mailgun/expiringdict
"""

from __future__ import annotations

from collections.abc import ItemsView, Iterator, KeysView, ValuesView
from typing import overload

class ExpiringDict[K, V]:
    """Thread-safe dict with auto-expiring entries.

    Entries expire after max_age_seconds and are evicted when max_len is exceeded.
    """

    def __init__(
        self,
        max_len: int,
        max_age_seconds: float,
        items: dict[K, V] | None = None,
    ) -> None: ...
    def __getitem__(self, key: K) -> V: ...
    def __setitem__(self, key: K, value: V) -> None: ...
    def __delitem__(self, key: K) -> None: ...
    def __contains__(self, key: object) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[K]: ...
    @overload
    def get(self, key: K) -> V | None: ...
    @overload
    def get(self, key: K, default: V) -> V: ...
    @overload
    def get(self, key: K, default: None) -> V | None: ...
    def pop(self, key: K, default: V | None = None) -> V | None: ...
    def keys(self) -> KeysView[K]: ...
    def values(self) -> ValuesView[V]: ...
    def items(self) -> ItemsView[K, V]: ...
    def clear(self) -> None: ...
    def copy(self) -> ExpiringDict[K, V]: ...
    def ttl(self, key: K) -> float | None:
        """Return remaining TTL in seconds for key, or None if expired/missing."""
        ...

    def items_with_timestamp(self) -> list[tuple[K, V, float]]:
        """Return list of (key, value, timestamp) tuples."""
        ...
