"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from collections.abc import Mapping

from grok_kit_sdk import errors, models, utils
from grok_kit_sdk._hooks import HookContext
from grok_kit_sdk.types import UNSET, OptionalNullable
from grok_kit_sdk.utils.unmarshal_json_response import unmarshal_json_response

from .basesdk import BaseSDK


class Conversations(BaseSDK):
    def list_conversations(
        self,
        *,
        page_size: int | None = 60,
        page_token: str | None = None,
        filter_is_starred: bool | None = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: str | None = None,
        timeout_ms: int | None = None,
        http_headers: Mapping[str, str] | None = None,
    ) -> models.ConversationListResponse:
        r"""List conversations

        Returns a page of conversation summaries, ordered by modifyTime descending.
        Pagination via `pageToken`; `nextPageToken` in the response is the cursor for
        the next page (empty string when last page).


        :param page_size: Server caps observed at 60.
        :param page_token: Cursor from a prior response's `nextPageToken`.
        :param filter_is_starred: Restrict to starred conversations only.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.ListConversationsRequest(
            page_size=page_size,
            page_token=page_token,
            filter_is_starred=filter_is_starred,
        )

        req = self._build_request(
            method='GET',
            path='/rest/app-chat/conversations',
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header='user-agent',
            accept_header_value='application/json',
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ['429', '500', '502', '503', '504'])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or '',
                operation_id='listConversations',
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(['4XX', '5XX'], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, '200', 'application/json'):
            return unmarshal_json_response(models.ConversationListResponse, http_res)
        if utils.match_response(http_res, '4XX', '*'):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.GrokKitDefaultError('API error occurred', http_res, http_res_text)
        if utils.match_response(http_res, '5XX', '*'):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.GrokKitDefaultError('API error occurred', http_res, http_res_text)

        raise errors.GrokKitDefaultError('Unexpected response received', http_res)

    async def list_conversations_async(
        self,
        *,
        page_size: int | None = 60,
        page_token: str | None = None,
        filter_is_starred: bool | None = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: str | None = None,
        timeout_ms: int | None = None,
        http_headers: Mapping[str, str] | None = None,
    ) -> models.ConversationListResponse:
        r"""List conversations

        Returns a page of conversation summaries, ordered by modifyTime descending.
        Pagination via `pageToken`; `nextPageToken` in the response is the cursor for
        the next page (empty string when last page).


        :param page_size: Server caps observed at 60.
        :param page_token: Cursor from a prior response's `nextPageToken`.
        :param filter_is_starred: Restrict to starred conversations only.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.ListConversationsRequest(
            page_size=page_size,
            page_token=page_token,
            filter_is_starred=filter_is_starred,
        )

        req = self._build_request_async(
            method='GET',
            path='/rest/app-chat/conversations',
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header='user-agent',
            accept_header_value='application/json',
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ['429', '500', '502', '503', '504'])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or '',
                operation_id='listConversations',
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(['4XX', '5XX'], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, '200', 'application/json'):
            return unmarshal_json_response(models.ConversationListResponse, http_res)
        if utils.match_response(http_res, '4XX', '*'):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.GrokKitDefaultError('API error occurred', http_res, http_res_text)
        if utils.match_response(http_res, '5XX', '*'):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.GrokKitDefaultError('API error occurred', http_res, http_res_text)

        raise errors.GrokKitDefaultError('Unexpected response received', http_res)

    def get_conversation(
        self,
        *,
        conversation_id: str,
        include_workspaces: bool | None = True,
        include_task_result: bool | None = True,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: str | None = None,
        timeout_ms: int | None = None,
        http_headers: Mapping[str, str] | None = None,
    ) -> models.ConversationDetailResponse:
        r"""Get conversation metadata

        Returns metadata for a single conversation. Note `_v2` suffix.

        :param conversation_id:
        :param include_workspaces:
        :param include_task_result:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetConversationRequest(
            conversation_id=conversation_id,
            include_workspaces=include_workspaces,
            include_task_result=include_task_result,
        )

        req = self._build_request(
            method='GET',
            path='/rest/app-chat/conversations_v2/{conversationId}',
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header='user-agent',
            accept_header_value='application/json',
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ['429', '500', '502', '503', '504'])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or '',
                operation_id='getConversation',
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(['4XX', '5XX'], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, '200', 'application/json'):
            return unmarshal_json_response(models.ConversationDetailResponse, http_res)
        if utils.match_response(http_res, '4XX', '*'):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.GrokKitDefaultError('API error occurred', http_res, http_res_text)
        if utils.match_response(http_res, '5XX', '*'):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.GrokKitDefaultError('API error occurred', http_res, http_res_text)

        raise errors.GrokKitDefaultError('Unexpected response received', http_res)

    async def get_conversation_async(
        self,
        *,
        conversation_id: str,
        include_workspaces: bool | None = True,
        include_task_result: bool | None = True,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: str | None = None,
        timeout_ms: int | None = None,
        http_headers: Mapping[str, str] | None = None,
    ) -> models.ConversationDetailResponse:
        r"""Get conversation metadata

        Returns metadata for a single conversation. Note `_v2` suffix.

        :param conversation_id:
        :param include_workspaces:
        :param include_task_result:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetConversationRequest(
            conversation_id=conversation_id,
            include_workspaces=include_workspaces,
            include_task_result=include_task_result,
        )

        req = self._build_request_async(
            method='GET',
            path='/rest/app-chat/conversations_v2/{conversationId}',
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header='user-agent',
            accept_header_value='application/json',
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ['429', '500', '502', '503', '504'])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or '',
                operation_id='getConversation',
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(['4XX', '5XX'], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, '200', 'application/json'):
            return unmarshal_json_response(models.ConversationDetailResponse, http_res)
        if utils.match_response(http_res, '4XX', '*'):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.GrokKitDefaultError('API error occurred', http_res, http_res_text)
        if utils.match_response(http_res, '5XX', '*'):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.GrokKitDefaultError('API error occurred', http_res, http_res_text)

        raise errors.GrokKitDefaultError('Unexpected response received', http_res)

    def list_share_links(
        self,
        *,
        conversation_id: str,
        page_size: int | None = 100,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: str | None = None,
        timeout_ms: int | None = None,
        http_headers: Mapping[str, str] | None = None,
    ) -> models.ShareLinksResponse:
        r"""List share links for a conversation

        :param conversation_id:
        :param page_size:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.ListShareLinksRequest(
            conversation_id=conversation_id,
            page_size=page_size,
        )

        req = self._build_request(
            method='GET',
            path='/rest/app-chat/share_links',
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header='user-agent',
            accept_header_value='application/json',
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ['429', '500', '502', '503', '504'])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or '',
                operation_id='listShareLinks',
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(['4XX', '5XX'], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, '200', 'application/json'):
            return unmarshal_json_response(models.ShareLinksResponse, http_res)
        if utils.match_response(http_res, '4XX', '*'):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.GrokKitDefaultError('API error occurred', http_res, http_res_text)
        if utils.match_response(http_res, '5XX', '*'):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.GrokKitDefaultError('API error occurred', http_res, http_res_text)

        raise errors.GrokKitDefaultError('Unexpected response received', http_res)

    async def list_share_links_async(
        self,
        *,
        conversation_id: str,
        page_size: int | None = 100,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: str | None = None,
        timeout_ms: int | None = None,
        http_headers: Mapping[str, str] | None = None,
    ) -> models.ShareLinksResponse:
        r"""List share links for a conversation

        :param conversation_id:
        :param page_size:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.ListShareLinksRequest(
            conversation_id=conversation_id,
            page_size=page_size,
        )

        req = self._build_request_async(
            method='GET',
            path='/rest/app-chat/share_links',
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header='user-agent',
            accept_header_value='application/json',
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ['429', '500', '502', '503', '504'])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or '',
                operation_id='listShareLinks',
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(['4XX', '5XX'], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, '200', 'application/json'):
            return unmarshal_json_response(models.ShareLinksResponse, http_res)
        if utils.match_response(http_res, '4XX', '*'):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.GrokKitDefaultError('API error occurred', http_res, http_res_text)
        if utils.match_response(http_res, '5XX', '*'):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.GrokKitDefaultError('API error occurred', http_res, http_res_text)

        raise errors.GrokKitDefaultError('Unexpected response received', http_res)
