"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from collections.abc import Mapping

from grok_kit_sdk import errors, models, utils
from grok_kit_sdk._hooks import HookContext
from grok_kit_sdk.types import UNSET, OptionalNullable
from grok_kit_sdk.utils.unmarshal_json_response import unmarshal_json_response

from .basesdk import BaseSDK


class Messages(BaseSDK):
    def get_response_tree(
        self,
        *,
        conversation_id: str,
        include_threads: bool | None = True,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: str | None = None,
        timeout_ms: int | None = None,
        http_headers: Mapping[str, str] | None = None,
    ) -> models.ResponseTreeResponse:
        r"""Get conversation message tree

        Returns the response-tree for a conversation: a flat array of nodes, each with
        responseId + sender + parentResponseId. Reconstruct the conversation thread by
        following parent links from leaves up.


        :param conversation_id:
        :param include_threads:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetResponseTreeRequest(
            conversation_id=conversation_id,
            include_threads=include_threads,
        )

        req = self._build_request(
            method='GET',
            path='/rest/app-chat/conversations/{conversationId}/response-node',
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header='user-agent',
            accept_header_value='application/json',
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ['429', '500', '502', '503', '504'])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or '',
                operation_id='getResponseTree',
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(['4XX', '5XX'], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, '200', 'application/json'):
            return unmarshal_json_response(models.ResponseTreeResponse, http_res)
        if utils.match_response(http_res, '4XX', '*'):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.GrokKitDefaultError('API error occurred', http_res, http_res_text)
        if utils.match_response(http_res, '5XX', '*'):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.GrokKitDefaultError('API error occurred', http_res, http_res_text)

        raise errors.GrokKitDefaultError('Unexpected response received', http_res)

    async def get_response_tree_async(
        self,
        *,
        conversation_id: str,
        include_threads: bool | None = True,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: str | None = None,
        timeout_ms: int | None = None,
        http_headers: Mapping[str, str] | None = None,
    ) -> models.ResponseTreeResponse:
        r"""Get conversation message tree

        Returns the response-tree for a conversation: a flat array of nodes, each with
        responseId + sender + parentResponseId. Reconstruct the conversation thread by
        following parent links from leaves up.


        :param conversation_id:
        :param include_threads:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetResponseTreeRequest(
            conversation_id=conversation_id,
            include_threads=include_threads,
        )

        req = self._build_request_async(
            method='GET',
            path='/rest/app-chat/conversations/{conversationId}/response-node',
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header='user-agent',
            accept_header_value='application/json',
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ['429', '500', '502', '503', '504'])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or '',
                operation_id='getResponseTree',
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(['4XX', '5XX'], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, '200', 'application/json'):
            return unmarshal_json_response(models.ResponseTreeResponse, http_res)
        if utils.match_response(http_res, '4XX', '*'):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.GrokKitDefaultError('API error occurred', http_res, http_res_text)
        if utils.match_response(http_res, '5XX', '*'):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.GrokKitDefaultError('API error occurred', http_res, http_res_text)

        raise errors.GrokKitDefaultError('Unexpected response received', http_res)

    def load_messages(
        self,
        *,
        conversation_id: str,
        response_ids: list[str],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: str | None = None,
        timeout_ms: int | None = None,
        http_headers: Mapping[str, str] | None = None,
    ) -> models.LoadResponsesResponse:
        r"""Load full message bodies for given responseIds

        Returns the full payload (text + metadata) for the supplied responseIds.
        Server cap on responseIds per call has not been empirically determined;
        observed working with up to 30 in a single request.


        :param conversation_id:
        :param response_ids:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.LoadMessagesRequest(
            conversation_id=conversation_id,
            body=models.LoadResponsesRequest(
                response_ids=response_ids,
            ),
        )

        req = self._build_request(
            method='POST',
            path='/rest/app-chat/conversations/{conversationId}/load-responses',
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header='user-agent',
            accept_header_value='application/json',
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body, False, False, 'json', models.LoadResponsesRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ['429', '500', '502', '503', '504'])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or '',
                operation_id='loadMessages',
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(['4XX', '5XX'], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, '200', 'application/json'):
            return unmarshal_json_response(models.LoadResponsesResponse, http_res)
        if utils.match_response(http_res, '4XX', '*'):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.GrokKitDefaultError('API error occurred', http_res, http_res_text)
        if utils.match_response(http_res, '5XX', '*'):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.GrokKitDefaultError('API error occurred', http_res, http_res_text)

        raise errors.GrokKitDefaultError('Unexpected response received', http_res)

    async def load_messages_async(
        self,
        *,
        conversation_id: str,
        response_ids: list[str],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: str | None = None,
        timeout_ms: int | None = None,
        http_headers: Mapping[str, str] | None = None,
    ) -> models.LoadResponsesResponse:
        r"""Load full message bodies for given responseIds

        Returns the full payload (text + metadata) for the supplied responseIds.
        Server cap on responseIds per call has not been empirically determined;
        observed working with up to 30 in a single request.


        :param conversation_id:
        :param response_ids:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.LoadMessagesRequest(
            conversation_id=conversation_id,
            body=models.LoadResponsesRequest(
                response_ids=response_ids,
            ),
        )

        req = self._build_request_async(
            method='POST',
            path='/rest/app-chat/conversations/{conversationId}/load-responses',
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header='user-agent',
            accept_header_value='application/json',
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body, False, False, 'json', models.LoadResponsesRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ['429', '500', '502', '503', '504'])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or '',
                operation_id='loadMessages',
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(['4XX', '5XX'], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, '200', 'application/json'):
            return unmarshal_json_response(models.LoadResponsesResponse, http_res)
        if utils.match_response(http_res, '4XX', '*'):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.GrokKitDefaultError('API error occurred', http_res, http_res_text)
        if utils.match_response(http_res, '5XX', '*'):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.GrokKitDefaultError('API error occurred', http_res, http_res_text)

        raise errors.GrokKitDefaultError('Unexpected response received', http_res)
